API 2744 Medication Request Count
department-of-veterans-affairs/health-apis-data-query pull request #602
Opened 2020-10-05 18:00 UTC by that-guy-is-it

2020-10-05 18:31 UTC, jhulbert-va requested changes
When making new methods, try to keep with the same naming convention as the already existing methods to avoid confusion.

2020-10-05 18:31 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationrequest/R4MedicationRequestController.java
> +          ctx.getTotalRequests(),
`totalCount` is probably better to keep with `totalPages`.

2020-10-05 18:31 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationrequest/R4MedicationRequestController.java
> +                  (double) medicationOrderSupport().numMedicationOrdersForPatient() / count()));
?

2020-10-05 18:31 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationrequest/R4MedicationRequestController.java
> +    long getTotalOrderRecords() {
`medicationOrderCount`

2020-10-05 18:31 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationrequest/R4MedicationRequestController.java
> +    long getTotalStatementRecords() {
`medicationStatementCount`

2020-10-05 18:31 UTC, jhulbert-va commented on data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medicationrequest/R4MedicationRequestControllerTest.java
> +                    controller().searchByPatient("p0", 1, 15).total(),
There's a better way to do this. You definitely shouldn't be making a second call to the controller in order to determine the count.

2020-10-05 19:50 UTC, jhulbert-va commented on data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medicationrequest/R4MedicationRequestControllerTest.java
> +                        .size(),
Why repeat what you could pull into a var?
```
var expectedTotalCount = p0.size();
```

2020-10-05 20:03 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationrequest/R4MedicationRequestController.java
> +              medicationStatementSupport().numMedicationStatementsForPatient() / (double) count());
Is there significance to moving the `(double)` from the `long` to the `int`?

2020-10-05 20:07 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationrequest/R4MedicationRequestController.java
> +              medicationStatementSupport().numMedicationStatementsForPatient() / (double) count());
It said the opposite diff and I asked him to change it...

2020-10-05 20:07 UTC, jhulbert-va commented on data-query/src/test/java/gov/va/api/health/dataquery/service/controller/medicationrequest/R4MedicationRequestControllerTest.java
> +                    controller().searchByPatient("p0", 1, 15).total(),
https://github.com/department-of-veterans-affairs/health-apis-data-query/pull/602#discussion_r499790594

2020-10-05 20:07 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationrequest/R4MedicationRequestController.java
> +              medicationStatementSupport().numMedicationStatementsForPatient() / (double) count());
https://github.com/department-of-veterans-affairs/health-apis-data-query/pull/602#discussion_r499790594

2020-10-05 20:47 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationrequest/R4MedicationRequestController.java
> +              medicationStatementSupport().numMedicationStatementsForPatient() / (double) count());
That was in a different method. (`totalPages()` vs `lastPageWithMedicationStatement()`)

2020-10-05 20:48 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationrequest/R4MedicationRequestController.java
> +              medicationStatementSupport().numMedicationStatementsForPatient() / (double) count());
I don't have strong feelings on it, but if there's no particular reason to change it, don't.

2020-10-05 20:51 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationrequest/R4MedicationRequestController.java
> +    long medicationOrderCount() {
Isn't this equivalent to `numMedicationOrdersForPatient()`?

2020-10-05 20:51 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationrequest/R4MedicationRequestController.java
> +    long medicationStatementCount() {
ditto `numMedicationStatementsForPatient()`

2020-10-05 20:52 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationrequest/R4MedicationRequestController.java
> +      return (statements + orders);
unnecessary parentheses

2020-10-05 21:00 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationrequest/R4MedicationRequestController.java
> +    int totalCount() {
Can we call this `totalRecords()` instead? `totalCount()` is a little confusing because we're already using `count` to represent page size.

2020-10-05 22:01 UTC, jhulbert-va submitted a review, later dismissed
If @jblefkove-va is okay with it, I think it looks good now.

2020-10-06 00:06 UTC, jblefkove-va approved these changes

2020-10-06 00:07 UTC, merged