API-2657: R4PatientTransformer supports managingOrganization field
department-of-veterans-affairs/health-apis-data-query pull request #604
Opened 2020-10-07 15:38 UTC by jjabando1

2020-10-07 15:43 UTC, jhulbert-va requested changes
Test?

2020-10-07 15:46 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientTransformer.java
> +    if (managingOrganization == null) {
`managingOrganization` is an `Optional<String>` there is a better way to check this.

2020-10-07 15:46 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientTransformer.java
> +    if (managingOrganization == null) {
null or empty

2020-10-07 16:02 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientTransformer.java
> +    if (managingOrganization == null) {
Where does `Datamart.create()` and `R4.create()` come from? Are they populating the managingOrganziation field?

2020-10-07 16:08 UTC, jjabando1 commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientTransformer.java
> +    if (managingOrganization == null) {
Ah ok those are taken from PatientSamples. I think I need to update
public gov.va.api.health.r4.api.resources.Patient patient()'s returned Patient builder to include managingOrganization

2020-10-07 19:15 UTC, jjabando1 commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientTransformer.java
> +    if (managingOrganization == null) {
So I assumed the better way to check was:
return managingOrganization.isPresent()
        ? Reference.builder().reference(managingOrganization.get()).build()
        : null;

This change causes most of the Controller and Transformer unit tests to fail. NullPointerExceptions for calls involving R4PatientTransformer.builder() and the controller(). I have no idea what is causing them to go null.

2020-10-07 20:33 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientTransformer.java
> +    if (managingOrganization == null) {
`Transformers.isBlank()` is the best way to verify that an Optional is both non-null and non-empty.

However, the fact that `datamart.managingOrganization()` is returning a null reference is also troubling. The different `DatamartXXX` model classes are supposed to include lazily-initializing getters for their `Optional` fields, e.g. https://github.com/department-of-veterans-affairs/health-apis-data-query/blob/master/data-query/src/main/java/gov/va/api/health/dataquery/service/controller/allergyintolerance/DatamartAllergyIntolerance.java#L46

The fact that `DatamartPatient` is not doing this for `managingOrganization` is an oversight and should be corrected.

2020-10-07 20:33 UTC, bschofield-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientTransformer.java
> +    if (managingOrganization == null) {
Your reference is incomplete.

You would not be first person to ever want to convert a DatamartReference into an R4 Reference. This method can be exactly one line about 41 characters long.

Here's a hint
```
$ git grep DatamartReference data-query/src/main/java/ | grep R4
```

2020-10-07 20:35 UTC, bschofield-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientTransformer.java
> +  private Reference managingOrganization() {
The big problem... you're adding production code, but you're not adding tests.

2020-10-07 20:36 UTC, bschofield-va submitted a review, later dismissed
how about tests?

2020-10-07 21:20 UTC, jjabando1 commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientTransformer.java
> +    if (managingOrganization == null) {
Should I go ahead and provide those lazy getters for the Optional fields in DatamartPatient?

2020-10-07 21:21 UTC, jjabando1 commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientTransformer.java
> +    if (managingOrganization == null) {
In DatamartPatient, managingOrganization is of type Optional<String>, so I am not sure where I should be doing any kind of DatamartReference to R4Reference conversion. In creating my Reference object, should I just assign Reference's display field to the managingOrganization string, rather than the reference field?

2020-10-07 21:29 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientTransformer.java
> +    if (managingOrganization == null) {
Yes, add the lazy getters

2020-10-08 14:40 UTC, bschofield-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientTransformer.java
> +  private Reference managingOrganization() {
You haven't actually added any tests specifically for this.

2020-10-08 14:42 UTC, bschofield-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientTransformer.java
> +    if (managingOrganization == null) {
My point about the the 41 character line to implement this method has been ignored.
See https://github.com/department-of-veterans-affairs/health-apis-data-query/blob/master/data-query/src/main/java/gov/va/api/health/dataquery/service/controller/R4Transformers.java#L66

```
   return asReference(datamart.managingOrganization());
```

2020-10-08 14:44 UTC, bschofield-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientTransformer.java
> +  private Reference managingOrganization() {
Changes this to be packaged protected and add explicit tests to verify the the couple of possible cases: null, partially populated, fully populated.

2020-10-09 15:33 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientTransformer.java
> +        .managingOrganization(managingOrganization(datamart.managingOrganization()))
It's more consistent for this method to remain non-static and access `datamart.managingOrganization()` internally. (In your unit test, you can set the `datamart` field on the transformer with the full test patient object and override just the `managingOrganization` field like so: `Datamart.create().patient().managingOrganization(...)`)

2020-10-09 19:17 UTC, jblefkove-va approved these changes

2020-10-09 19:25 UTC, bschofield-va requested changes
hol up

2020-10-09 20:00 UTC, bschofield-va approved these changes

2020-10-09 20:06 UTC, merged