API-3710: swagger and capability/conformance verification
department-of-veterans-affairs/health-apis-data-query pull request #623
Opened 2020-11-23 18:04 UTC by jjabando1

2020-11-25 19:29 UTC, ilaflamme-va requested changes

2020-11-25 19:29 UTC, ilaflamme-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/metadata/Dstu2MetadataController.java
> +        return ImmutableSet.of(
We do not want to advertise our patient searching. Only search by ID.

2020-11-30 17:13 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/metadata/Dstu2MetadataController.java
> -                .search(diagnosticReportSearchParams())
Instead of removing the method entirely, I think that the switch should just fall through.

2020-12-01 14:00 UTC, bschofield-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/metadata/Dstu2MetadataController.java
>        case PATIENT:
always document fall through so everyone knows it was intentional. Your IDE should have been warning you.
```
case Patient:
  // fall through
case CLINICIAN:
```

2020-12-01 14:03 UTC, bschofield-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/metadata/Dstu2MetadataController.java
>        case PATIENT:
Actually... what's the point of the case statement at all.

2020-12-01 14:05 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/metadata/Dstu2MetadataController.java
>        case PATIENT:
That's on me. I asked him to keep the case statements for any resource with more than id/identifier. I feel it's more clear as to the intent.

2020-12-01 14:07 UTC, bschofield-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/metadata/Dstu2MetadataController.java
> +                .search(
This bothers me now... previously we used methods (e.g., `conditionSearchParams()`) to decide what parameters apply to what mode. But now those methods do no logic. They _always_ return the same set, and _now_ we have a two different ways of doing the same thing. For resources that have constant parameters regardless of the mode (patient/clinician) we sometimes build the set in place, sometime call a method to build a set.

Pick one way and do it. Either inline the method return values here or move all set creation to methods. If you keep the methods, you need to remove the case statements from all them that do not make any decisions.

2020-12-01 14:08 UTC, bschofield-va submitted a review, later dismissed
do not like methods for search parameters with unnecessary switch statements

2020-12-02 20:45 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/metadata/Dstu2MetadataController.java
> +    IDENTIFIER("identifier", SearchParamType.string),
Identifier is _technically_ a token.

2020-12-02 20:48 UTC, eclendenning-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/metadata/Dstu2MetadataController.java
> +    IDENTIFIER("identifier", SearchParamType.string),
while this is true, isnt the point of the story to bring it into line with what we currently support? We currently don't support that as a token.

2020-12-02 20:49 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/metadata/Dstu2MetadataController.java
> +    IDENTIFIER("identifier", SearchParamType.string),
Gender is marked as a token, but we only support it as a string as well. ¯\_(ツ)_/¯

2020-12-02 20:52 UTC, eclendenning-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/metadata/Dstu2MetadataController.java
> +    IDENTIFIER("identifier", SearchParamType.string),
Thats a good point. I think `gender` should also be a string in the swagger as well then.

2020-12-02 20:54 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/metadata/Dstu2MetadataController.java
> +    IDENTIFIER("identifier", SearchParamType.string),
I don't know that I agree. If we were to do that, then the metadata basically says "we're not fhir compliant".

2020-12-02 20:56 UTC, eclendenning-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/metadata/Dstu2MetadataController.java
> +    IDENTIFIER("identifier", SearchParamType.string),
I think its a little bit of false advertising otherwise. I'll defer to @ramosan-lit .

2020-12-02 22:14 UTC, eclendenning-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/metadata/Dstu2MetadataController.java
> +    IDENTIFIER("identifier", SearchParamType.string),
After re-reading the definition of the string search without `:exact` I think Josh is correct.

2020-12-03 14:16 UTC, eclendenning-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/metadata/R4MetadataController.java
>      ID("_id", SearchParamType.string),
`category` and `_id` should also be tokens

2020-12-03 14:20 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/metadata/R4MetadataController.java
>      ID("_id", SearchParamType.string),
I thought `_id` was a string and `identifier` is a token?

https://www.hl7.org/fhir/search.html#id

2020-12-03 14:21 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/metadata/R4MetadataController.java
>      ID("_id", SearchParamType.string),
https://www.hl7.org/fhir/resource.html#search

2020-12-03 20:54 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/metadata/R4MetadataController.java
>      ID("_id", SearchParamType.string),
@jjabando1 what about dstu2 category?

2020-12-04 13:24 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/metadata/Dstu2MetadataController.java
>      ID("_id", SearchParamType.string),
`_id` is a token.

2020-12-04 13:28 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/metadata/R4MetadataController.java
>      INTENT("intent", SearchParamType.string),
`intent` is a token.

https://www.hl7.org/fhir/medicationrequest.html#search

2020-12-04 17:23 UTC, jhulbert-va approved these changes
LGTM

2020-12-04 18:38 UTC, merged