API-3085-condition-search-capabilities
department-of-veterans-affairs/health-apis-data-query pull request #642
Opened 2021-01-06 19:01 UTC by jhulbert-va

# [API-3085](https://vajira.max.gov/browse/API-3085)

2021-01-07 14:47 UTC, eclendenning-va requested changes

2021-01-07 14:47 UTC, eclendenning-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/condition/R4ConditionController.java
> +  private String toDatamartCategory(String category) {
toDatamartCategoryName ?

2021-01-07 14:47 UTC, eclendenning-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/condition/R4ConditionController.java
> +        .onExplicitSystemAndAnyCode(s -> List.of("active", "resolved"))
I liked your use of the enums for category and I think the same should be applied to clinical status.

2021-01-07 15:33 UTC, eclendenning-va submitted a review, later dismissed

2021-01-07 21:54 UTC, eclendenning-va submitted a review, later dismissed

2021-01-11 14:01 UTC, bschofield-va approved these changes

2021-01-11 14:01 UTC, merged