API 4618 - Vulcanized Location and modified tests and samples accordingly.
department-of-veterans-affairs/health-apis-data-query pull request #700
Opened 2021-04-19 15:31 UTC by that-guy-is-it

2021-04-19 17:11 UTC, jblefkove-va commented
The `connection refused` errors in the ITs on jenkins are really an indication that the server is failing to start. You can see that error earlier in the console output, before the individual tests are run:
```
10:59:55  [INFO] Starting process: data-query
10:59:55  [INFO] Using working directory for this process: /var/****_home/workspace/_API-4618-Location-Facilities-ID/data-query-tests/target
11:00:27  [ERROR] 
11:00:27  java.lang.RuntimeException: Process was not healthy even after 30 seconds
11:00:27      at com.bazaarvoice.maven.plugin.process.ProcessHealthCondition.waitSecondsUntilHealthy (ProcessHealthCondition.java:30)
11:00:27      at com.bazaarvoice.maven.plugin.process.ProcessStartMojo.startProcess (ProcessStartMojo.java:43)
11:00:27      at com.bazaarvoice.maven.plugin.process.ProcessStartMojo.execute (ProcessStartMojo.java:26)
11:00:27      at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
11:00:27      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
11:00:27      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
11:00:27      at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
11:00:27      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
11:00:27      at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
11:00:27      at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
11:00:27      at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
11:00:27      at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
11:00:27      at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
11:00:27      at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
11:00:27      at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
11:00:27      at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
11:00:27      at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
11:00:27      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
11:00:27      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
11:00:27      at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
11:00:27      at java.lang.reflect.Method.invoke (Method.java:564)
11:00:27      at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
11:00:27      at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
11:00:27      at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
11:00:27      at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

As for why the server is failing to start, the error is not in the jenkins console output, but you can see it in the ITs `data-query.log` file when running locally:
```
2021-04-19 13:03:46.037  WARN 10792 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: Ambiguous mapping. Cannot map 'r4LocationController' method 
gov.va.api.health.dataquery.service.controller.location.R4LocationController#readRaw(String, HttpServletResponse)
to {GET /r4/Location/{publicId}, produces [application/json || application/fhir+json]}: There is already 'r4LocationController' bean method
gov.va.api.health.dataquery.service.controller.location.R4LocationController#read(String) mapped.
2021-04-19 13:03:46.037  INFO 10792 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2021-04-19 13:03:46.043  INFO 10792 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2021-04-19 13:03:46.072  INFO 10792 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2021-04-19 13:03:46.113  INFO 10792 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-04-19 13:03:46.138 ERROR 10792 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: Ambiguous mapping. Cannot map 'r4LocationController' method 
gov.va.api.health.dataquery.service.controller.location.R4LocationController#readRaw(String, HttpServletResponse)
to {GET /r4/Location/{publicId}, produces [application/json || application/fhir+json]}: There is already 'r4LocationController' bean method
gov.va.api.health.dataquery.service.controller.location.R4LocationController#read(String) mapped.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	...
Caused by: java.lang.IllegalStateException: Ambiguous mapping. Cannot map 'r4LocationController' method 
gov.va.api.health.dataquery.service.controller.location.R4LocationController#readRaw(String, HttpServletResponse)
to {GET /r4/Location/{publicId}, produces [application/json || application/fhir+json]}: There is already 'r4LocationController' bean method
gov.va.api.health.dataquery.service.controller.location.R4LocationController#read(String) mapped.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855) ~[spring-beans-5.2.7.RELEASE.jar!/:5.2.7.RELEASE] [12 skipped]
	...
	... 24 common frames omitted
```

2021-04-20 12:53 UTC, jhulbert-va requested changes

2021-04-20 12:53 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/location/R4LocationController.java
> +        .toPatientId(e -> Optional.of(e.cdwId()))
Location doesn't have a patient id.

2021-04-20 12:53 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/location/R4LocationController.java
> +        .replaceReferences(x -> Stream.empty())
Location has the managingOrg references that need to be replaced. If you look at the DatamartLocation object, any `DatamartReference` should be in this stream.

2021-04-20 12:53 UTC, jhulbert-va commented on data-query/src/test/java/gov/va/api/health/dataquery/service/controller/location/R4LocationControllerTest.java
>  @ExtendWith(SpringExtension.class)
I think both of these annotations can get gone.

2021-04-20 12:53 UTC, jhulbert-va commented on data-query/src/test/java/gov/va/api/health/dataquery/service/controller/location/R4LocationControllerTest.java
> +  private static ResourceIdentity id(String cdwId) {
This method should (and already does) exist in the samples class.

2021-04-20 12:53 UTC, jhulbert-va commented on data-query/src/test/java/gov/va/api/health/dataquery/service/controller/location/R4LocationControllerTest.java
> +  static String json(Object o) {
Samesies.

2021-04-20 12:53 UTC, jhulbert-va commented on data-query/src/test/java/gov/va/api/health/dataquery/service/controller/location/R4LocationControllerTest.java
> +  private static Registration registration(String cdwId, String publicId) {
This boi too.

2021-04-20 12:53 UTC, jhulbert-va commented on data-query/src/test/java/gov/va/api/health/dataquery/service/controller/location/R4LocationControllerTest.java
> +        "?address-postalcode=76504"
What about combinations of these?

2021-04-20 12:53 UTC, jhulbert-va commented on data-query/src/test/java/gov/va/api/health/dataquery/service/controller/location/R4LocationControllerTest.java
> +    when(ids.lookup("x")).thenReturn(List.of(id("loc1")));
Instead of `x`, how about something like `loc1` and `ploc1` (the prefix `p` for public). It also helps to show your intent.

2021-04-20 12:53 UTC, jhulbert-va commented on data-query/src/test/java/gov/va/api/health/dataquery/service/controller/location/R4LocationControllerTest.java
> +    when(ids.lookup("x")).thenReturn(List.of(id("loc1")));
Here too.

2021-04-20 20:39 UTC, jhulbert-va approved these changes
LGTM

2021-04-21 13:33 UTC, merged