API-3090: vulcanize procedure
department-of-veterans-affairs/health-apis-data-query pull request #710
Opened 2021-04-30 15:00 UTC by jabando-va

2021-04-30 16:58 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/procedure/R4ProcedureController.java
> +        .toPatientId(e -> Optional.empty())
Procedure is a patient centric resource. It should definitely populate this.

2021-04-30 16:58 UTC, jhulbert-va commented on data-query/src/test/java/gov/va/api/health/dataquery/service/controller/procedure/R4ProcedureControllerTest.java
>    HttpServletResponse response = mock(HttpServletResponse.class);
I think this is only used in one test. Can we move it down there?

2021-05-03 14:22 UTC, bschofield-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/procedure/R4ProcedureController.java
> +                    (DateMapping.PredicateFactory<Long>)
eh? we need to discuss this

2021-05-03 14:40 UTC, bschofield-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/procedure/R4ProcedureController.java
> +                    (DateMapping.PredicateFactory<Long>)
Enhance Vulcan to support `Mapping.dateAsLong("date","performOnEpochTime")` to avoid this ugliness of having to repeat all of this logic.

2021-05-03 14:40 UTC, bschofield-va requested changes
Date processing need to be in Vulcan itself

2021-05-10 19:13 UTC, eclendenning-va approved these changes

2021-05-10 19:24 UTC, merged