API-6605: Implement new appointment status logic using visitsid
department-of-veterans-affairs/health-apis-data-query pull request #731
Opened 2021-05-14 13:07 UTC by apeirats-va

Also see: https://github.com/department-of-veterans-affairs/health-apis-datamart-synthetic-records/pull/136

This PR implements logic described at bottom of the `visitSid` documentation: https://github.com/department-of-veterans-affairs/health-apis-data/blob/master/Documentation/Appt%20Status%20Logic%20Using%20VisitSID.md

2021-05-14 21:21 UTC, bschofield-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/appointment/R4AppointmentTransformer.java
> +        .status(status(dm.start(), dm.status(), dm.visitSid(), Instant.now()))
No need to pass `now` around. Just use create it where it is needed.

2021-05-14 22:14 UTC, apeirats-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/appointment/R4AppointmentTransformer.java
> +        .status(status(dm.start(), dm.status(), dm.visitSid(), Instant.now()))
This is meant to support unit tests, since the new logic is based on comparing the appt time to the current timestamp.

Alternatively, the Transformer could use a class-level Supplier, `Supplier<Instant> now = Instant::now;` which the unit test can override:
```
R4AppointmentTransformer.builder()
  ...
  .now(() -> Instant.parse(...))
  .build();
```

2021-05-17 14:35 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/appointment/R4AppointmentTransformer.java
>     * </ul>
this javadoc should also be updated

2021-05-17 15:18 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/appointment/R4AppointmentTransformer.java
> +    if (visitSid.isPresent()) {
If `visitSid` is not present, is that equivalent to `0`?

2021-05-17 15:19 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/appointment/R4AppointmentTransformer.java
> +    if (start.isEmpty() || start.get().isAfter(now)) {
This may not be a realistic case, but I think this should be `start.isPresent() && start.get().isAfter(now)`. e.g. if an appointment has not start time but does have `visitSid >0`, I would still expect that to be `fulfilled`.

2021-05-17 15:22 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/appointment/R4AppointmentTransformer.java
>      switch (status.get()) {
could we do `status.orElse("NO ACTION TAKEN")` here to eliminate the above check?

2021-05-17 17:16 UTC, apeirats-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/appointment/R4AppointmentTransformer.java
> +    if (start.isEmpty() || start.get().isAfter(now)) {
I went with the logic described here: https://github.com/department-of-veterans-affairs/health-apis-data/blob/master/Documentation/Appt%20Status%20Logic%20Using%20VisitSID.md#proposed-additional-logic-using-appointmentdatetimeutc-and-visitsid

It's possible for a future appointment to have a `visitSid > 0`. It should be ignored according to the above, and always treated as `booked`. Should we revisit that?

2021-05-17 17:19 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/appointment/R4AppointmentTransformer.java
> +    if (start.isEmpty() || start.get().isAfter(now)) {
I missed the note about future appointments having a visitSid. Leave it as is then.

2021-05-17 17:21 UTC, apeirats-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/appointment/R4AppointmentTransformer.java
> +    if (visitSid.isPresent()) {
It _should_ always be provided. It _should_ never be == 0 (_should_ always be either negative or positive).

If not present or null, I think it's indicative of an error and treated as such. I don't feel too strongly about it, though. I could treat it as a `-1`, along with a `log.warn(...)` message.

2021-05-17 19:12 UTC, apeirats-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/appointment/R4AppointmentTransformer.java
> +        .status(status(dm.start(), dm.status(), dm.visitSid(), Instant.now()))
Going with a different approach- the test determines past/future times through `Instant.now().plus(Duration.ofDays(...))` instead of passing in explicit timestamps.

2021-05-17 19:18 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/appointment/R4AppointmentTransformer.java
> +    if (allBlank(start, status)) {
should `visitSid` also be included?

2021-05-17 19:18 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/appointment/R4AppointmentTransformer.java
> +    switch (status.orElse("NO ACTION TAKEN")) {
with this defaulting you can remove the `status.isEmpty()` check above

2021-05-17 19:22 UTC, apeirats-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/appointment/R4AppointmentTransformer.java
> +    if (allBlank(start, status)) {
I think we can remove this check now that `status` defaults to `NO ACTION TAKEN`. Before, I just needed at least `status` or `start` to be provided. I think `visitSid` would've been useless on its own. 

By assuming a default value for `status` it removes the need for this check.

2021-05-17 20:06 UTC, jblefkove-va commented
Need to regenerate `mitre.mv.db` due to a merge... otherwise this looks ready to go

2021-05-17 20:38 UTC, jblefkove-va approved these changes

2021-05-17 20:56 UTC, ilaflamme-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/appointment/R4AppointmentTransformer.java
> +    if (visitSid.isPresent()) {
Since we need the `visitSid` to make the correct decision for `Status`, and because `Status` is a required field, if it is missing, we should error.

2021-05-17 21:06 UTC, ilaflamme-va commented
Looks good to me.

2021-05-17 21:06 UTC, ilaflamme-va approved these changes

2021-05-17 21:17 UTC, bschofield-va requested changes
just pausing this one minute

2021-05-17 21:33 UTC, bschofield-va approved these changes

2021-05-17 22:32 UTC, merged