API-11214-pracititioner-and-practitioner-role-transformer-update
department-of-veterans-affairs/health-apis-data-query pull request #810
Opened 2021-11-10 20:10 UTC by taylorrassmannlibertyits

Updated transformers with new datamart fields for practitioner.

2021-11-10 20:11 UTC, taylorrassmannlibertyits commented
Hold off on merge until https://github.com/department-of-veterans-affairs/health-apis-datamart-synthetic-records/pull/213 is completed

2021-11-12 15:10 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/Dstu2PractitionerTransformer.java
> +    return Period.builder().start(start).end(end).build();
`Optional` has a nice map function you could use which will only perform the action if the optional is present. I think it reads better than the ternary:
```
period.start().map(LocalDate::toString).orElse(null);
```

2021-11-12 16:04 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/Dstu2PractitionerTransformer.java
> +        .end(maybePeriod.get().end().map(LocalDate::toString).orElse(null))
You'll still want to check that both start and end aren't blank.
```
   if (isBlank(maybePeriod) || allBlank(maybePeriod.get().start(), maybePeriod.get().end())) {
      return null;
    }
```

2021-11-12 16:16 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/Dstu2PractitionerTransformer.java
> +  static Period period(Optional<DatamartPractitioner.Period> maybePeriod) {
Just a note (no need to change it), `Optional.map` is also great to avoid optionals in your method signatures. e.g.
```
Line 54: 
    .period(address.period().map(this::period).orElse(null))

Line 94-97:
    Period period(DatamartPractitioner.Period period) {
        if (isBlank(period) || allBlank(period.start(), period.end())) {
          return null;
        }
```

2021-11-12 16:16 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/Dstu2PractitionerTransformer.java
> +  static List<Practitioner.Qualification> qualification(Optional<String> maybeQualificationText) {
We normally don't make theses methods static. It looks like they're only static for use in the tests. Instead, these can be non-static and the test class should have a `_transformer` method that creates a transformer that can then call the methods.
```
assertThat(_transformer().qualification(Optional.of("x"))).isEqualTo(expected);
```

2021-11-12 18:07 UTC, taylorrassmannlibertyits commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/Dstu2PractitionerTransformer.java
> +  static Period period(Optional<DatamartPractitioner.Period> maybePeriod) {
I like this way more, since I'm in the area still, I'll update to be cleaner for the future

2021-11-12 18:53 UTC, jhulbert-va approved these changes
LGTM

2021-11-15 16:18 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/R4PractitionerTransformer.java
> +            address.period())) {
There is a subtle bug here. `address.period()` may be present with both its `start` and `end` null, so it will still map to a null FHIR period

2021-11-15 17:39 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/R4PractitionerTransformer.java
> +            address.period())) {
Shouldn't the period method deal with this?

2021-11-15 17:46 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/R4PractitionerTransformer.java
> +            address.period())) {
Right, if the only field present is a period with no `start` or `end`, we do not want to create an empty address

2021-11-15 18:45 UTC, jblefkove-va requested changes
R4 only

2021-11-15 18:54 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/Dstu2PractitionerTransformer.java
> +            address.period().map(this::period))) {
Not a fan of this. You'll end up doing the mapping twice if everything isn't blank.

2021-11-15 19:23 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/Stu3PractitionerTransformer.java
> +  Period period(DatamartPractitioner.Period period) {
cruft

2021-11-15 19:25 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/practitioner/R4PractitionerTransformer.java
> +            address.period().map(this::period))) {
To Josh's point, let's split this check:
```
if (address == null) return null
period = address.period().map(...)
if (allBlank(..., period)) return null
```

2021-11-15 19:34 UTC, jblefkove-va approved these changes
:shipit:

2021-11-15 19:46 UTC, jhulbert-va approved these changes

2021-11-15 19:54 UTC, merged