API 11229 Immunization Transformer Dose Quantity
department-of-veterans-affairs/health-apis-data-query pull request #817
Opened 2021-11-19 16:40 UTC by that-guy-is-it

2021-11-19 16:49 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/immunization/R4ImmunizationTransformer.java
> +    if (!doseQuantity.isPresent() || isBlank(doseQuantity.get().value())) {
Can we split this check and pull out `doseQuantity.get()` so we avoid repeating that five times?

2021-11-19 16:50 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/immunization/R4ImmunizationTransformer.java
> +    if (!doseQuantity.isPresent() || isBlank(doseQuantity.get().value())) {
Even though a quantity with no value is not meaningful, this should probably be an `allBlank()` check for every field on `doseQuantity`

2021-11-19 17:19 UTC, jblefkove-va requested changes
DQ PRs are on hold for the moment

2021-11-19 18:54 UTC, jblefkove-va commented
Unit tests? I'd expect `ImmunizationSamples` to be updated

2021-11-19 19:19 UTC, taylorrassmannlibertyits commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/immunization/R4ImmunizationTransformer.java
> +    if (!maybeDoseQuantity.isPresent()) {
I think you can use `isEmpty` here and you don't have to have a negative statement

2021-11-19 20:12 UTC, taylorrassmannlibertyits commented on data-query/src/test/java/gov/va/api/health/dataquery/service/controller/immunization/ImmunizationSamples.java
> +              .value(maybeValue)
Can you put `Optional.ofNullable(value);` here?

2021-11-19 20:14 UTC, jblefkove-va commented on data-query/src/test/java/gov/va/api/health/dataquery/service/controller/immunization/ImmunizationSamples.java
> +    SimpleQuantity doseQuantity(Double value) {
Since this is test data and you control all of the calls to it, why not do `doseQuantity(double value)` and remove the null check?

2021-11-19 21:30 UTC, jblefkove-va commented on data-query/src/test/java/gov/va/api/health/dataquery/service/controller/immunization/ImmunizationSamples.java
> +              .code(Optional.of("ng/mL"))
nitpick, but stick to value/unit/system/code order

2021-11-19 21:30 UTC, jblefkove-va commented on data-query/src/test/java/gov/va/api/health/dataquery/service/controller/immunization/ImmunizationSamples.java
> +          .code("ng/mL")
ditto order

2021-11-22 13:47 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/immunization/R4ImmunizationTransformer.java
> +  static SimpleQuantity doseQuantity(Optional<DatamartImmunization.Quantity> maybeDoseQuantity) {
This shouldn't be static

2021-11-22 13:55 UTC, jblefkove-va commented on data-query/src/test/java/gov/va/api/health/dataquery/service/controller/immunization/ImmunizationSamples.java
> +    Optional<DatamartImmunization.Quantity> doseQuantity(Double value) {
this should also be populated in `DatamartImmunization immunization(...)` method

2021-11-22 16:25 UTC, jhulbert-va approved these changes
:shipit:

2021-11-22 16:26 UTC, jblefkove-va approved these changes
:shipit:

2021-11-22 16:27 UTC, merged