Api 11683 encounter controller and raw endpoint
department-of-veterans-affairs/health-apis-data-query pull request #829
Opened 2021-12-08 23:59 UTC by taylorrassmannlibertyits

https://vajira.max.gov/browse/API-11683

2021-12-09 20:03 UTC, jhulbert-va reviewed
Make sure you're using getters when digging into the objects, and `isBlank` for all strings, lists, and optionals.

2021-12-09 20:03 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +    return asReference(patient);
`asReference` is already null safe, so this method is redundant.

2021-12-10 14:16 UTC, taylorrassmannlibertyits commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +  static Coding encounterClass(String encounterClass) {
Removed unnecessary `static`s

2021-12-10 14:20 UTC, taylorrassmannlibertyits commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +    String lastUpdated = asDateTimeString(dmLastUpdated);
This is handled by `asDateTimeString`

2021-12-10 15:30 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +    return Coding.builder().display(encounterClass).build();
No null check here... `encounterClass` is a required field? If so, let's make that explicit with `checkState()`

2021-12-10 15:30 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +    if (hospitalization.dischargeDisposition.isEmpty()) {
getter

2021-12-10 15:34 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +        asCodeableConceptWrapping(hospitalization.dischargeDisposition.get());
I think this would be cleaner with `Optional.map()`:
```
hospitalization
.dischargeDisposition()
.map(dd -> asCodeableConceptWrapping(dd))
.map(cc -> Hospitalization.builder().dischargeDisposition(cc).build())
.orElse(null)
```

2021-12-10 15:36 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +    if (isBlank(locations)) {
FWIW you can remove this check. `locations` list is lazily-initialized in `DatamartEncounter` and will never be `null`, and if it is empty, line 62 will correctly handle that to return `null`

2021-12-10 15:41 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +                .system("urn:oid:2.16.840.1.113883.3.8901.3.1.9000010.8007")
I think the url version of this is more consistent with the other resources

2021-12-10 15:42 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +    return emptyToNull(reasonCodes.stream().map(rc -> reasonCode(rc)).collect(Collectors.toList()));
static import `toList()`

2021-12-10 15:43 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +    return CodeableConcept.builder().text(serviceType.toString()).build();
does enum `toString()` account for hyphen vs underscore in certain values?

2021-12-10 15:44 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +    if (serviceProvider == null) {
`asReference()` already handles the null

2021-12-10 16:19 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +    return Coding.builder().display(encounterClass).build();
On second thought, an IllegalStateException is probably going to become a 500 error that is not super-clear to the user. I think just a comment that `encounterClass` is known to be non-null is sufficient.

2021-12-10 19:28 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +    return Coding.builder().display(encounterClass).build();
In the past, we traditionally don't throw even for "required" fields. Our general process is, "give all the data we can, even if it's incomplete".

2021-12-10 19:44 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterController.java
> +                    resource.participants().stream()
Is there any possibility `locations()` or `participants()` can return `null`?

2021-12-10 19:44 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +    if (hospitalization.dischargeDisposition().isEmpty()) {
Two things: one, what if hospitalization is blank? two, use `isBlank()` on `dischargeDisposition`.

2021-12-10 19:44 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +    if (participants.isEmpty()) {
`isBlank()`

2021-12-10 19:44 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +    if (participant == null) {
`asReference` does this check.

2021-12-10 19:44 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +    return emptyToNull(participants.stream().map(p -> participant(p)).collect(toList()));
For what it's worth, I think this would read better without the participant method:
```
participants.stream()
    .map(Participant::participant)
    .map(R4Transformers::asReference)
    .filter(Objects::nonNull)
    .map(reference -> Participant.builder().individual(reference).build())
    toList()
```

2021-12-10 19:44 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +    if (reasonCodes.isEmpty()) {
`isBlank`

2021-12-10 19:44 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +  }
Why the separate method for one line?

2021-12-10 19:44 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +    return CodeableConcept.builder().text(serviceType.toString().replace("_", "-")).build();
I don't think this is a safe assumption to make. Why not add a constructor/method in the enum?

2021-12-10 19:44 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +    return EnumSearcher.of(Encounter.Status.class).find(status.toString().replace("_", "-"));
Same here.

2021-12-10 19:48 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterController.java
> +                    resource.participants().stream()
Yes... use `Safe.stream()`

2021-12-13 13:36 UTC, taylorrassmannlibertyits commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +    if (hospitalization.dischargeDisposition().isEmpty()) {
The null case should be handled by line 156:
`.map(this::hospitalization).orElse(null))`

Since `dischargeDisposition` is lazy initialized, is `isBlank()` required?

2021-12-13 15:31 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +    if (isBlank(hospitalization.dischargeDisposition())) {
if `hospitalization` is null, you're gonna NPE here.

2021-12-13 15:31 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +  }
The same thing that applied to `participants` applies here.

2021-12-13 15:31 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +    return participants.stream()
You'll still want to `emptyToNull` this.

2021-12-13 15:31 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +    return EnumSearcher.of(Encounter.Status.class).find(status.toString());
Is your overriding `toString`, gonna break the enumSearcher?

2021-12-13 15:31 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +    return EnumSearcher.of(Encounter.Status.class).find(status.toString());
Is there a test that tests all values can be mapped? If not, you should only need to create a ParameterizedTest with an enum source verifying non-null (`EnumSearch.find()` will throw if no value is found).

2021-12-13 15:31 UTC, jhulbert-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +        .subject(subject(datamart.patient()))
Why not just `asReference` here?

2021-12-13 15:31 UTC, jhulbert-va commented on data-query/src/test/java/gov/va/api/health/dataquery/service/controller/encounter/DatamartEncounterTest.java
> +    assertThat(DatamartEncounter.Status.finished.toString()).isEqualTo("finished");
Let's split this into two tests, one per enum.

2021-12-13 16:54 UTC, jhulbert-va commented on data-query/src/test/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformerTest.java
> +            .datamart(DatamartEncounter.builder().encounterClass("AMB").build())
With `encounterClass` there, this isn't technically testing an empty DM Encoutner.

2021-12-13 16:54 UTC, jhulbert-va commented on data-query/src/test/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformerTest.java
> +    assertThat(tx(EncounterSamples.Datamart.create().encounter()).status(status)).isNotNull();
I'd create a default `tx()` that assumes your basic default sample encounter.

2021-12-13 18:53 UTC, jhulbert-va commented on data-query/src/test/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformerTest.java
> +    assertThat(tx().serviceType(serviceType)).isNotNull();
Not super sure this is testing anything. You already know you're passing a non-null value, so it'll always return a coding.

2021-12-13 18:54 UTC, jhulbert-va approved these changes

2021-12-13 19:00 UTC, taylorrassmannlibertyits commented on data-query/src/test/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformerTest.java
> +    assertThat(tx().serviceType(serviceType)).isNotNull();
Coverage :'(

2021-12-13 19:59 UTC, jhulbert-va submitted a review, later dismissed

2021-12-14 17:24 UTC, jblefkove-va requested changes
Apologies for the delay in getting back to this... I do have a few more comments, mainly about the Datamart enum `toString()` methods. In the interest of getting this merged ASAP, I will make a push shortly to address my feedback.

2021-12-14 17:24 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/DatamartEncounter.java
> +    public String toString() {
I don't think this is the right approach. None of the enums on the other Datamart model classes define `toString()` methods. I would rather the transformer class itself encapsulate this map or do whatever it needs to to map the enum correctly.

2021-12-14 17:24 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/DatamartEncounter.java
> +    public String toString() {
This `toString()` is unnecessary... the mapping for Encounter status is from one enum type to another, and `EnumSearcher` already looks for the `@JsonProperty` annotation and handles underscore messiness.

2021-12-14 17:24 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +    // encounterClass is known to be non-null however this null check prevents an empty coding
nitpick, but if we've standardized on null checking all transformer method parameters, this comment isn't really necessary

2021-12-14 17:24 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +    if (hospitalization == null || isBlank(hospitalization.dischargeDisposition())) {
`hospitalization.dischargeDisposition()` is an optional, so you don't need to check it up here; the optionals chain below will handle it being empty

2021-12-14 17:24 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterTransformer.java
> +        .hospitalization(datamart.hospitalization().map(this::hospitalization).orElse(null))
this line is awkward compared to the rest of the method... it would be cleaner to have `hospitalization(datamart.hospitalization())` and let the method handle the optional

2021-12-14 17:24 UTC, jblefkove-va commented on data-query/src/test/java/gov/va/api/health/dataquery/service/controller/encounter/DatamartEncounterTest.java
> +  void serviceTypeToString() {
These tests are at the wrong level of detail. What we really want to test is that the transformer maps Encounter status and serviceType correctly; whether the transformer is relying on `toString()` to achieve that is irrelevant

2021-12-14 17:24 UTC, jblefkove-va commented on data-query/src/test/java/gov/va/api/health/dataquery/service/controller/encounter/EncounterSamples.java
> +    private gov.va.api.health.r4.api.datatypes.Period period() {
Since we don't have to worry about conflicting imports for different FHIR versions (DSTU2 vs R4) in this class, you might as well import R4 Period too

2021-12-14 17:35 UTC, jblefkove-va approved these changes
:shipit:

2021-12-14 17:36 UTC, merged