API-11889: Observation referencerange null checks for quantity value/code
department-of-veterans-affairs/health-apis-data-query pull request #836
Opened 2021-12-20 19:08 UTC by jabando-va

2021-12-20 19:13 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/observation/R4ObservationTransformer.java
> +      if (quantity.code() == null) {
If code is null, we don't want to populate system either, even if that's non-null?

2021-12-20 19:14 UTC, jabando-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/observation/R4ObservationTransformer.java
> +      if (quantity.code() == null) {
Yeah, if I understood the story right: https://vajira.max.gov/browse/API-11889

2021-12-20 19:32 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/observation/R4ObservationTransformer.java
> +      if (quantity.code() == null) {
Let's remove the above `else` to avoid nesting conditionals

2021-12-20 19:38 UTC, bschofield-va requested changes
This is missing DSTU2, which is version we really need it in since it's what Apple is using and this issue was raised by Apple.

2021-12-21 14:19 UTC, eclendenning-va approved these changes

2021-12-21 14:36 UTC, merged