Api 16504 r4 return 400 no params
department-of-veterans-affairs/health-apis-data-query pull request #938
Opened 2022-06-13 18:32 UTC by taylorrassmannlibertyits

https://vajira.max.gov/browse/API-16504

2022-06-14 12:02 UTC, jblefkove-va commented on data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/r4/MedicationRequestIT.java
> +    verifyAll( // MedicationRequest Public Id
these inline comments moved

2022-06-14 12:06 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/appointment/R4AppointmentController.java
> +                    "date", "_id", "identifier", "_lastUpdated", "location", "patient"),
This is not correct... it is not valid to specify only `date` or `_lastUpdated`. The required (but mutally-exclusive) parameters are `_id`, `identifier`, and `patient`

2022-06-14 12:37 UTC, taylorrassmannlibertyits commented on data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/r4/PatientIT.java
> +        test(400, OperationOutcome.class, "Patient?given={given}", testIds.pii().given()),
`given` is no longer a valid parameter to give an empty bundle so I changed the status to 400

2022-06-14 13:24 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/appointment/R4AppointmentController.java
> +                    "date", "_id", "identifier", "_lastUpdated", "location", "patient"),
On second look. `Appointment` is a special case; `_lastUpdated` and `location` are valid parameters by themselves

2022-06-14 13:24 UTC, taylorrassmannlibertyits commented on data-query-tests/src/test/java/gov/va/api/health/dataquery/tests/r4/PatientIT.java
> +        test(400, OperationOutcome.class, "Patient?given={given}", testIds.pii().given()),
Since the unknown case is being tests with the new test in this IT I think I'm going to remove this test scenario entirely

2022-06-15 21:41 UTC, jblefkove-va requested changes
Noted a few more parameters to tweak; I will address and merge

2022-06-15 21:41 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/encounter/R4EncounterController.java
> +                atLeastOneParameterOf("date", "_id", "identifier", "patient"),
date requires patient

2022-06-15 21:41 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/location/R4LocationController.java
> +                    "patient"),
not patient

2022-06-15 21:41 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/medicationrequest/R4MedicationRequestController.java
> +                atLeastOneParameterOf("_id", "identifier", "intent", "patient"),
intent requires patient

2022-06-15 21:41 UTC, jblefkove-va commented on data-query/src/main/java/gov/va/api/health/dataquery/service/controller/patient/R4PatientController.java
>                  parametersNeverSpecifiedTogether("name", "family"),
These two `parametersNeverSpecifiedTogether()` can be combined... i.e. you can specify exactly one of the four. Also, you should not specify `organization` with the `_id` or `identifier`, but may do so with `name` or `family`. And below, `birthdate` and `gender` may also be specified with `organization`

2022-06-15 21:47 UTC, merged